export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FETCH_FORUMS_START = 'FETCH_FORUMS_START';
export const FETCH_FORUMS_SUCCESS = 'FETCH_FORUMS_SUCCESS';
export const FETCH_FORUMS_FAIL = 'FETCH_FORUMS_FAIL';

export const FETCH_FORUM_START = 'FETCH_FORUM_START';
export const FETCH_FORUM_SUCCESS = 'FETCH_FORUM_SUCCESS';
export const FETCH_FORUM_FAIL = 'FETCH_FORUM_FAIL';

export const FETCH_POST_START = 'FETCH_POST_START';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';