//ui
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

//auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

//forum
export const SET_FORUM_SORT = 'SET_FORUM_SORT';
export const SET_FORUM_TOP = 'SET_FORUM_TOP';
export const REQUEST_FORUMS_START = 'REQUEST_FORUMS_START';
export const REQUEST_FORUMS_SUCCESS = 'REQUEST_FORUMS_SUCCESS';
export const REQUEST_FORUMS_FAILURE = 'REQUEST_FORUMS_FAILURE';
export const REQUEST_FORUM_START = 'REQUEST_FORUM_START';
export const REQUEST_FORUM_SUCCESS = 'REQUEST_FORUM_SUCCESS';
export const REQUEST_FORUM_FAILURE = 'REQUEST_FORUM_FAILURE';

//post
export const SET_HOME_SORT = 'SET_HOME_SORT';
export const SET_HOME_TOP = 'SET_HOME_TOP';
export const SET_POST_SORT = 'SET_POST_SORT';
export const SET_POST_TOP = 'SET_POST_TOP';
export const REQUEST_POSTS_START = 'REQUEST_POSTS_START';
export const REQUEST_POSTS_SUCCESS = 'REQUEST_POSTS_SUCCESS';
export const REQUEST_POSTS_FAILURE = 'REQUEST_POSTS_FAILURE';
export const REQUEST_POST_START = 'REQUEST_POST_START';
export const REQUEST_POST_SUCCESS = 'REQUEST_POST_SUCCESS';
export const REQUEST_POST_FAILURE = 'REQUEST_POST_FAILURE';
export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';
export const CREATE_POST_RESET = 'CREATE_POST_RESET';
export const UPDATE_POST_START = 'UPDATE_POST_START';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';
export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

//comment
export const REQUEST_COMMENTS_START = 'REQUEST_COMMENTS_START';
export const REQUEST_COMMENTS_SUCCESS = 'REQUEST_COMMENTS_SUCCESS';
export const REQUEST_COMMENTS_FAILURE = 'REQUEST_COMMENTS_FAILURE';
export const CREATE_COMMENT_START = 'CREATE_COMMENT_START';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';
export const UPDATE_COMMENT_START = 'UPDATE_COMMENT_START';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAILURE = 'UPDATE_COMMENT_FAILURE';
export const DELETE_COMMENT_START = 'DELETE_COMMENT_START';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

//postVote
export const CREATE_POSTVOTE_START = 'CREATE_POSTVOTE_START';
export const CREATE_POSTVOTE_SUCCESS = 'CREATE_POSTVOTE_SUCCESS';
export const CREATE_POSTVOTE_FAILURE = 'CREATE_POSTVOTE_FAILURE';
export const UPDATE_POSTVOTE_START = 'UPDATE_POSTVOTE_START';
export const UPDATE_POSTVOTE_SUCCESS = 'UPDATE_POSTVOTE_SUCCESS';
export const UPDATE_POSTVOTE_FAILURE = 'UPDATE_POSTVOTE_FAILURE';
export const DELETE_POSTVOTE_START = 'DELETE_POSTVOTE_START';
export const DELETE_POSTVOTE_SUCCESS = 'DELETE_POSTVOTE_SUCCESS';
export const DELETE_POSTVOTE_FAILURE = 'DELETE_POSTVOTE_FAILURE';

//commentVote
export const CREATE_COMMENTVOTE_START = 'CREATE_COMMENTVOTE_START';
export const CREATE_COMMENTVOTE_SUCCESS = 'CREATE_COMMENTVOTE_SUCCESS';
export const CREATE_COMMENTVOTE_FAILURE = 'CREATE_COMMENTVOTE_FAILURE';
export const UPDATE_COMMENTVOTE_START = 'UPDATE_COMMENTVOTE_START';
export const UPDATE_COMMENTVOTE_SUCCESS = 'UPDATE_COMMENTVOTE_SUCCESS';
export const UPDATE_COMMENTVOTE_FAILURE = 'UPDATE_COMMENTVOTE_FAILURE';
export const DELETE_COMMENTVOTE_START = 'DELETE_COMMENTVOTE_START';
export const DELETE_COMMENTVOTE_SUCCESS = 'DELETE_COMMENTVOTE_SUCCESS';
export const DELETE_COMMENTVOTE_FAILURE = 'DELETE_COMMENTVOTE_FAILURE';

//savedPost
export const CREATE_SAVEDPOST_START = 'CREATE_SAVEDPOST_START';
export const CREATE_SAVEDPOST_SUCCESS = 'CREATE_SAVEDPOST_SUCCESS';
export const CREATE_SAVEDPOST_FAILURE = 'CREATE_SAVEDPOST_FAILURE';
export const DELETE_SAVEDPOST_START = 'DELETE_SAVEDPOST_START';
export const DELETE_SAVEDPOST_SUCCESS = 'DELETE_SAVEDPOST_SUCCESS';
export const DELETE_SAVEDPOST_FAILURE = 'DELETE_SAVEDPOST_FAILURE';